version: 2

models:
  - name: sales_summary
    description: "Sales summary by region and category"

    columns:
      - name: region
        tests:
          - not_null

      - name: category
        tests:
          - not_null

      - name: total_sales
        tests:
          - not_null

      - name: total_profit
        tests:
          - not_null